Parameters:
  S3BucketName:
    Type: String
    Default: s3-techtalk-aws-serverless-data
    
Resources:
  ###### EMR Serverless
  # IAM Role for EMR serverless
  EMRServerlessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: role-techtalk-emr-serverless
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - emr-serverless.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: 'EMRServerlessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 
                  - 's3:*'
                  - 'logs:*'
                Resource: '*'  

  EMRServerlessApplication:
    Type: 'AWS::EMRServerless::Application'
    Properties:
      Name: techtalk-emrsrvless-app-sample
      ReleaseLabel: emr-6.15.0
      Type: Spark
      AutoStartConfiguration:
        Enabled: true
      AutoStopConfiguration:
        Enabled: true
        IdleTimeoutMinutes: 15
      MaximumCapacity:
        Cpu: '40 vCPU'
        Memory: '3000 GB'
        Disk: '20000 GB'      
 
Outputs:
  TechTalkEMRServerlessApplicationId:
    Value: !Ref EMRServerlessApplication
    Export:
      Name: TechTalkEMRServerlessApplicationId
